# Generated by Django 2.1.5 on 2019-01-10 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='name')),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Amount')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_set', to='bank.Bank', verbose_name='bank')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ('name',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('bank', 'name')},
        ),
        migrations.AlterIndexTogether(
            name='account',
            index_together={('bank', 'name')},
        ),
    ]
