# Generated by Django 2.1.5 on 2019-01-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190111_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cap',
            field=models.PositiveSmallIntegerField(default=0, help_text='monthly spending cap', verbose_name='spending cap'),
        ),
    ]
