# Generated by Django 2.1.5 on 2019-01-10 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0001_initial'),
        ('account', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='name')),
                ('amount', models.PositiveSmallIntegerField(db_index=True, verbose_name='amount')),
                ('slug', models.SlugField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ('-date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.Transaction')),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('transaction.transaction',),
        ),
        migrations.CreateModel(
            name='Foresight',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.Transaction')),
                ('frequency', models.CharField(choices=[('d', 'daily'), ('w', 'weekly'), ('m', 'monthly'), ('y', 'yearly')], db_index=True, max_length=1, verbose_name='frequency')),
                ('active', models.BooleanField(db_index=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'foresight',
                'verbose_name_plural': 'foresights',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('transaction.transaction',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_set', to='account.Account', verbose_name='account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_transaction.transaction_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_set', to='source.Source', verbose_name='source'),
        ),
        migrations.AlterIndexTogether(
            name='transaction',
            index_together={('source', 'account'), ('source', 'name'), ('source', 'account', 'name'), ('account', 'name')},
        ),
    ]
