# Generated by Django 2.1.5 on 2019-01-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20190111_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directdebit',
            name='active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='active'),
        ),
    ]
